import './globals.css'
import { Inter } from '@next/font/google'
export const metadata = {
  title: 'TintTool - Home',
  description: 'Generated by create next app'
}
const interStyles = Inter({
  subsets: ['latin']
})
export default function RootLayout ({ children }) {
  return (
    <html lang='en' className={interStyles.className}>
      <body>{children}</body>
    </html>
  )
}
